// Code generated by MockGen. DO NOT EDIT.
// Source: backend-challenge/internal/db (interfaces: OrderDao,ProductDao,CouponDao,SearchResult)

// Package mocks is a generated GoMock package.
package mocks

import (
	db "backend-challenge/internal/db"
	openapi "backend-challenge/internal/generated/openapi"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderDao is a mock of OrderDao interface.
type MockOrderDao struct {
	ctrl     *gomock.Controller
	recorder *MockOrderDaoMockRecorder
}

// MockOrderDaoMockRecorder is the mock recorder for MockOrderDao.
type MockOrderDaoMockRecorder struct {
	mock *MockOrderDao
}

// NewMockOrderDao creates a new mock instance.
func NewMockOrderDao(ctrl *gomock.Controller) *MockOrderDao {
	mock := &MockOrderDao{ctrl: ctrl}
	mock.recorder = &MockOrderDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderDao) EXPECT() *MockOrderDaoMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderDao) CreateOrder(arg0 context.Context, arg1 db.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderDaoMockRecorder) CreateOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderDao)(nil).CreateOrder), arg0, arg1)
}

// MockProductDao is a mock of ProductDao interface.
type MockProductDao struct {
	ctrl     *gomock.Controller
	recorder *MockProductDaoMockRecorder
}

// MockProductDaoMockRecorder is the mock recorder for MockProductDao.
type MockProductDaoMockRecorder struct {
	mock *MockProductDao
}

// NewMockProductDao creates a new mock instance.
func NewMockProductDao(ctrl *gomock.Controller) *MockProductDao {
	mock := &MockProductDao{ctrl: ctrl}
	mock.recorder = &MockProductDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductDao) EXPECT() *MockProductDaoMockRecorder {
	return m.recorder
}

// GetAllProducts mocks base method.
func (m *MockProductDao) GetAllProducts(arg0 context.Context) ([]db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts", arg0)
	ret0, _ := ret[0].([]db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockProductDaoMockRecorder) GetAllProducts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockProductDao)(nil).GetAllProducts), arg0)
}

// GetProduct mocks base method.
func (m *MockProductDao) GetProduct(arg0 context.Context, arg1 string) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0, arg1)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockProductDaoMockRecorder) GetProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockProductDao)(nil).GetProduct), arg0, arg1)
}

// MockCouponDao is a mock of CouponDao interface.
type MockCouponDao struct {
	ctrl     *gomock.Controller
	recorder *MockCouponDaoMockRecorder
}

// MockCouponDaoMockRecorder is the mock recorder for MockCouponDao.
type MockCouponDaoMockRecorder struct {
	mock *MockCouponDao
}

// NewMockCouponDao creates a new mock instance.
func NewMockCouponDao(ctrl *gomock.Controller) *MockCouponDao {
	mock := &MockCouponDao{ctrl: ctrl}
	mock.recorder = &MockCouponDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCouponDao) EXPECT() *MockCouponDaoMockRecorder {
	return m.recorder
}

// SearchForCouponInGivenFiles mocks base method.
func (m *MockCouponDao) SearchForCouponInGivenFiles(arg0 context.Context, arg1 openapi.OrderReq) (db.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchForCouponInGivenFiles", arg0, arg1)
	ret0, _ := ret[0].(db.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchForCouponInGivenFiles indicates an expected call of SearchForCouponInGivenFiles.
func (mr *MockCouponDaoMockRecorder) SearchForCouponInGivenFiles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchForCouponInGivenFiles", reflect.TypeOf((*MockCouponDao)(nil).SearchForCouponInGivenFiles), arg0, arg1)
}

// MockSearchResult is a mock of SearchResult interface.
type MockSearchResult struct {
	ctrl     *gomock.Controller
	recorder *MockSearchResultMockRecorder
}

// MockSearchResultMockRecorder is the mock recorder for MockSearchResult.
type MockSearchResultMockRecorder struct {
	mock *MockSearchResult
}

// NewMockSearchResult creates a new mock instance.
func NewMockSearchResult(ctrl *gomock.Controller) *MockSearchResult {
	mock := &MockSearchResult{ctrl: ctrl}
	mock.recorder = &MockSearchResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchResult) EXPECT() *MockSearchResultMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockSearchResult) Validate() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockSearchResultMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockSearchResult)(nil).Validate))
}
